Feat/encrypt: support encrypt when sync
juanjiTech/termium-proto pull request #11
Opened 2023-11-05 13:32 UTC by GoldenSheep402

创建新组的时候生成密钥链
获取加密的密钥是根据提供的gid获取
修改master_key时，将服务器上用户相关的密钥全部更新

2023-11-06 06:25 UTC, asjdf requested changes

2023-11-06 07:00 UTC, GoldenSheep402 commented on proto/sync/v1/group.proto
> +    string public_key = 9;  // 公钥 这里不存私钥，私钥加密后存在用户手上
数据库存了个加密了私钥

2023-11-06 07:58 UTC, GoldenSheep402 commented on proto/sync/v1/group.proto
> +    string public_key = 9;  // 公钥 这里不存私钥，私钥加密后存在用户手上
用户keyChain的允许改公钥吗，改这个的话会有点小复杂

2023-11-06 08:13 UTC, asjdf requested changes

2023-11-06 08:13 UTC, asjdf commented on proto/sync/v1/group.proto
> +    string publicKey = 9;  // 公钥 这里不存私钥，私钥加密后存在用户手上
这里注释改一下，加密后有一份是存服务器的，只不过在用户表的那边

2023-11-06 08:13 UTC, asjdf commented on proto/sync/v1/sync_service.proto
> +  // 更新组信息 如果创建一个新的组
如果？没打完？

2023-11-06 08:13 UTC, asjdf commented on proto/sync/v1/sync_service.proto
>  message UpdateRequest {
建议请求名称打全，UpdateRequest的翻译结果是“更新请求”，单独看很难看出来是update啥

2023-11-06 08:13 UTC, asjdf commented on proto/sync/v1/sync_service.proto
> +  string encrypted_privateKey = 4;  // 创建者的私钥
这个不发到这里，这个发到个人的“组织私钥钱包”（或者保险箱？看个人理解吧x）里头

2023-11-06 08:13 UTC, asjdf commented on proto/sync/v1/sync_service.proto
> +  string encrypted_key = 1; // 被master_key加密后的密钥，用于解密后续的密文,返回给本地以再次存储。
这个返回来好像没啥意义？

2023-11-06 08:15 UTC, asjdf commented on proto/sync/v1/sync_service.proto
>  message UpdateRequest {
看起来是历史遗留的问题x 之前只有update一点东西x

2023-11-06 08:20 UTC, GoldenSheep402 commented on proto/sync/v1/sync_service.proto
>  message UpdateRequest {
这个命名 确实难绷了

2023-11-06 08:41 UTC, GoldenSheep402 commented on proto/sync/v1/group.proto
> +    string publicKey = 9;  // 公钥 这里不存私钥，私钥加密后存在用户手上
fine

2023-11-06 08:44 UTC, GoldenSheep402 commented on proto/sync/v1/sync_service.proto
> +  string encrypted_privateKey = 4;  // 创建者的私钥
publicKey作为组的基本信息一起，加密的priKey放创建者那边？可以吗

2023-11-06 08:58 UTC, asjdf commented on proto/sync/v1/sync_service.proto
> +  string encrypted_privateKey = 4;  // 创建者的私钥
对的，加密的priKey放在每个团队成员账户下，私钥分别用团队成员各自的公钥加密（不用操心加密流程

2023-11-06 08:59 UTC, asjdf commented
<img width="516" alt="image" src="https://github.com/juanjiTech/jTerm-proto/assets/22193008/994517a1-f61e-40ce-97f4-0dbc67a039ae">

2023-11-11 10:41 UTC, asjdf requested changes

2023-11-11 14:40 UTC, GoldenSheep402 commented on proto/sync/v1/group.proto
> +    repeated GroupKeyChain group_keychain = 2;
打算是在管理这个组的地方用，管理员携带这个提交上去然后做存的处理，别的地方就用不到他

2023-11-11 14:50 UTC, GoldenSheep402 commented on proto/sync/v1/group.proto
> +    repeated GroupKeyChain group_keychain = 2;
就比如管理者想修改所有者，从这边可以提交数据上去修改

2023-11-13 06:52 UTC, asjdf commented on proto/sync/v1/group.proto
> +    repeated GroupKeyChain group_keychain = 2;
这个得走另外接口了吧（主要是说缝在同步里头意义不大？（到时候同步函数变得贼大 功能复杂

2023-11-13 07:16 UTC, GoldenSheep402 commented on proto/sync/v1/group.proto
> +    repeated GroupKeyChain group_keychain = 2;
可，有空就修一下

2023-11-14 01:44 UTC, asjdf commented
来观测一下进度x

2023-11-15 09:45 UTC, asjdf requested changes
还是有一些偏差，需要一个改以及沟通

2023-11-15 09:45 UTC, asjdf commented on proto/sync/v1/group.proto
> +    repeated GroupKeyChain group_keychain = 2;
还没改啊，还没改啊

2023-11-15 09:45 UTC, asjdf commented on proto/sync/v1/sync_service.proto
> +  repeated UserKeyWallet user_key_wallet_set = 4;
小驼峰

2023-11-15 09:45 UTC, asjdf commented on proto/sync/v1/sync_service.proto
> +  repeated UserKeyWallet user_key_wallet_set = 4;
小驼峰

2023-11-15 09:45 UTC, asjdf commented on proto/sync/v1/sync_service.proto
> +  repeated UserKeyWallet user_key_wallet_set = 4;
小驼峰

2023-11-15 09:45 UTC, asjdf commented on proto/sync/v1/sync_service.proto
> +  google.protobuf.Timestamp created_at = 4;
小驼峰

2023-11-15 09:45 UTC, asjdf commented on proto/sync/v1/sync_service.proto
> +  repeated UserKeyWallet user_key_wallet = 4;
小驼峰

2023-11-15 09:45 UTC, asjdf commented on proto/sync/v1/sync_service.proto
>      KnownHost known_host = 12;
现在所有字段都小驼峰

2023-11-15 09:45 UTC, asjdf commented on proto/sync/v1/sync_service.proto
>    repeated KnownHost known_host_set = 12;
小驼峰

2023-11-15 09:45 UTC, asjdf commented on proto/sync/v1/group.proto
> +    string member_id = 11;
小驼峰

2023-11-15 09:45 UTC, asjdf commented on proto/sync/v1/group.proto
> +message GroupKeyChain{
这东西我没明白作用啊

2023-11-15 09:45 UTC, asjdf commented on proto/sync/v1/group.proto
> +message GroupKeyChain{
sync的时候肯定还得鉴权，不能单靠key来管 另外key是在用户的keyWallet里头 而不是在群组下

2023-11-15 10:45 UTC, GoldenSheep402 commented on proto/sync/v1/group.proto
> +message GroupKeyChain{
这个PubKey是用来加密具体组的密钥，不是个人的

2023-11-15 11:16 UTC, GoldenSheep402 commented on proto/sync/v1/group.proto
> +message GroupKeyChain{
打算是用于加密组的组PubKey和组直接放一起 作为基本信息，PriKey直接存到用户KeyWallet下，鉴权的话涉及密钥操作就判断是否是管理和非管理的区别

2023-11-22 10:43 UTC, GoldenSheep402 commented
加邀请，接受，删除 这三个功能的接口吧

2023-11-22 11:03 UTC, daidr commented
________________________________
From: GoldenSheep ***@***.***>
Sent: Wednesday, November 22, 2023 10:44:08 AM
To: juanjiTech/termium-proto ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [juanjiTech/termium-proto] feat(encrypt): support encrypt when sync (PR #11)


加邀请，接受，删除 这三个功能的接口吧

—
Reply to this email directly, view it on GitHub<https://github.com/juanjiTech/termium-proto/pull/11#issuecomment-1822524874>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEOGQQVVF5YTNEQXQ3LSM33YFXJPRAVCNFSM6AAAAAA66K7BAWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRSGUZDIOBXGQ>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-11-22 11:35 UTC, GoldenSheep402 commented
草 看到了

2023-12-01 10:28 UTC, merged